# Generated by Django 5.0.7 on 2024-07-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="profile",
        ),
    ]
